### ISSUE TITLE
Add support for CSS-In-JS

### ISSUE THREAD

**Issue by jellydn** [ruilisi/css-checker#5]
Thank you for your awesome work. Just wondering if you could support CSS-in-js solutions like https://github.com/styled-components/styled-components or https://github.com/emotion-js/emotion  in your roadmap.

**Comment by zhcalvin** [comment]
Brillant idea. 

It's currently not supported yet, but I will do this soon.

**Comment by hophacker** [comment]
@jellydn css-in-js is now supported, check it out 😄

**Comment by zhcalvin** [comment]
Supported by: [feat: checks for styled components](https://github.com/ruilisi/css-checker/commit/818faef72cdfb30d409e54e1b926ce7a7a6ec922)

To Use:
```
css-checker -styled
```
Or  if you only need to check styled components:
```
css-checker -styled -css=false
```

**Comment by zhcalvin** [comment]
Supported by: [feat: checks for styled components](https://github.com/ruilisi/css-checker/commit/818faef72cdfb30d409e54e1b926ce7a7a6ec922)

To Use:
```
css-checker -styled
```
Or  if you only need to check styled-components:
```
css-checker -styled -css=false
```

**Comment by jellydn** [comment]
Awesome. Thanks.
