### ISSUE TITLE
Installation errors - arm64 not supported

### ISSUE THREAD

**Issue by wppoland** [ruilisi/css-checker#7]
Using `npm install -g css-checker-kit` to install css-checker, cause the following error message:
```
Installation is not supported for this architecture: arm64
Invalid inputs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! css-checker-kit@0.4.1 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the css-checker-kit@0.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by zhcalvin** [comment]
NPM package upgraded and arm64 is now supported. Thanks for your report, just try `npm install -g css-checker-kit` aagain.  @wppoland

**Comment by aeolusheath** [comment]
λ npm install -g css-checker-kit --registry=https://registry.npm.taobao.org

> css-checker-kit@0.4.2 postinstall C:\Program Files\nodejs\node_modules\css-checker-kit
> go-npm install

Downloading from URL: https://github.com/ruilisi/css-checker/releases/download/v0.4.1/css-checker_0.4.1_windows_amd64.tar.gz
Error downloading from URL: https://github.com/ruilisi/css-checker/releases/download/v0.4.1/css-checker_0.4.1_windows_amd64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! css-checker-kit@0.4.2 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the css-checker-kit@0.4.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by aeolusheath** [comment]
@zhcalvin  install failed , bro,help

λ npm install -g css-checker-kit --registry=https://registry.npm.taobao.org

> css-checker-kit@0.4.2 postinstall C:\Program Files\nodejs\node_modules\css-checker-kit
> go-npm install

Downloading from URL: https://github.com/ruilisi/css-checker/releases/download/v0.4.1/css-checker_0.4.1_windows_amd64.tar.gz
Error downloading from URL: https://github.com/ruilisi/css-checker/releases/download/v0.4.1/css-checker_0.4.1_windows_amd64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! css-checker-kit@0.4.2 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the css-checker-kit@0.4.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
